# Generated by Django 4.0.6 on 2022-07-25 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrable_app', '0002_employee_hr_jobs_rename_user_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job_Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('dob', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(max_length=100)),
                ('job_id', models.CharField(max_length=100)),
                ('cover_letter', models.CharField(max_length=10000)),
                ('status', models.CharField(default='Pending', max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Refferal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='jobs',
            name='email',
        ),
        migrations.RemoveField(
            model_name='jobs',
            name='password',
        ),
        migrations.RemoveField(
            model_name='jobs',
            name='private_key',
        ),
        migrations.AddField(
            model_name='jobs',
            name='date',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobs',
            name='description',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobs',
            name='location',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobs',
            name='requirements',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobs',
            name='responsibilities',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobs',
            name='salary',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
