# Generated by Django 4.0.6 on 2022-07-25 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrable_app', '0003_job_application_refferal_remove_jobs_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='refferal',
            name='name_of_referrer',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
