# Generated by Django 4.0.6 on 2022-07-31 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrable_app', '0005_admin_dob_admin_gender_admin_mobile_number_hr_dob_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.CharField(max_length=5000)),
                ('forWhom', models.CharField(max_length=100)),
            ],
        ),
    ]
