# Generated by Django 4.0.6 on 2022-07-31 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrable_app', '0007_job_application_jobname'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='joining_date',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hr',
            name='joining_date',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
