# Generated by Django 4.0.6 on 2022-07-31 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrable_app', '0008_employee_joining_date_hr_joining_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('checkin', models.CharField(max_length=100)),
                ('checkout', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('userid', models.CharField(max_length=100)),
            ],
        ),
    ]
