# Generated by Django 4.0.6 on 2022-07-31 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrable_app', '0009_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobs',
            old_name='location',
            new_name='city',
        ),
        migrations.RemoveField(
            model_name='jobs',
            name='date',
        ),
        migrations.AddField(
            model_name='jobs',
            name='enddate',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobs',
            name='startdate',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobs',
            name='state',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
