# Generated by Django 4.0.6 on 2022-07-31 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrable_app', '0010_rename_location_jobs_city_remove_jobs_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobs',
            name='responsibilities',
        ),
    ]
