# Generated by Django 4.0.6 on 2022-08-02 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrable_app', '0011_remove_jobs_responsibilities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='forWhom',
        ),
    ]
