# Generated by Django 4.0.6 on 2022-08-02 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrable_app', '0012_remove_quote_forwhom'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
