# Generated by Django 4.0.6 on 2022-08-04 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrable_app', '0014_job_application_rejected'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Job_Application_Rejected',
        ),
    ]
