# Generated by Django 4.0.6 on 2022-08-05 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrable_app', '0015_delete_job_application_rejected'),
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empname', models.CharField(max_length=100)),
                ('emp_id', models.CharField(max_length=100)),
                ('query_type', models.CharField(max_length=1000)),
                ('query', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('status', models.CharField(default='Pending', max_length=100)),
                ('hr_acknowledging', models.CharField(default='Pending', max_length=100)),
                ('hr_id', models.CharField(max_length=100)),
            ],
        ),
    ]
